services:
  web:
    depends_on:
      - puppeteer
    build: .
    ports:
      - "8080:8080"
    links:
      - puppeteer
  puppeteer:
    build:
      context: ./puppeteer
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
