services:
  web:
    depends_on:
      - puppeteer
    build: .
    ports:
      - "8080:8080"
  puppeteer:
    build:
      context: ./puppeteer
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
